"""user

Revision ID: 13acc0e35735
Revises: bd3148321d0c
Create Date: 2021-02-03 16:28:45.901952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13acc0e35735'
down_revision = 'bd3148321d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('job_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_categories_category'), 'job_categories', ['category'], unique=False)
    op.create_index(op.f('ix_job_categories_id'), 'job_categories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_categories_id'), table_name='job_categories')
    op.drop_index(op.f('ix_job_categories_category'), table_name='job_categories')
    op.drop_table('job_categories')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
