"""create tables

Revision ID: 13ff85cedaeb
Revises: fbebf09cd9f6
Create Date: 2021-02-03 15:49:40.102093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ff85cedaeb'
down_revision = 'fbebf09cd9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
