"""is_active default set to true

Revision ID: 66566e15072b
Revises: ad5055221a07
Create Date: 2021-02-03 16:47:08.124260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66566e15072b'
down_revision = 'ad5055221a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
