"""add created_date to user table

Revision ID: 8e028e93cb0b
Revises: 381db56b812d
Create Date: 2021-02-17 16:06:42.584799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e028e93cb0b'
down_revision = '381db56b812d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_date')
    # ### end Alembic commands ###
