"""is_active default set to false

Revision ID: ad5055221a07
Revises: f2679d505394
Create Date: 2021-02-03 16:32:02.901030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5055221a07'
down_revision = 'f2679d505394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
