"""add created_date to categories table

Revision ID: b08e7e3f5687
Revises: 8e028e93cb0b
Create Date: 2021-02-17 16:08:15.037302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08e7e3f5687'
down_revision = '8e028e93cb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_categories', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_categories', 'created_date')
    # ### end Alembic commands ###
