"""create tables

Revision ID: e6ceaef6002b
Revises: 13ff85cedaeb
Create Date: 2021-02-03 16:05:43.887157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ceaef6002b'
down_revision = '13ff85cedaeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
