"""jobcategory

Revision ID: f2679d505394
Revises: 13acc0e35735
Create Date: 2021-02-03 16:30:23.646656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2679d505394'
down_revision = '13acc0e35735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
