"""create tables

Revision ID: fbebf09cd9f6
Revises: 6187037ad86a
Create Date: 2021-02-03 15:43:39.615799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbebf09cd9f6'
down_revision = '6187037ad86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
